### ISSUE TITLE
After pruning the node, will it cause an underestimation of the influence spread?

### ISSUE THREAD

**Issue by Shi-D** [idea-iitd/GCOMB#9]
The paper lacks experiments to compare the influence spread with the baseline, so this problem confuses me.

**Comment by sahilm1992** [comment]
Hi,
Thanks for your interest in our paper.

We would like to clarify that the model prunes nodes that are unlikely to be a part of the solution set.  Hence, the expensive computations are only performed on nodes with a high potential of being part of the solution set.

However, the influence is computed using the entire graph.
